contract_analysis_task:
  description: >
    Analyze the contract and extract the key terms and conditions
  expected_output: >
    The key terms and conditions of the contract.  Make sure to include all monetary terms, dates, and any other relevant information.
  agent: contract_analyst

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
