chuck_norris_agent_task:
  description: >
    Research and find the latest Chuck Norris jokes.
  expected_output: >
    The list of Chuck Norris jokes you have found.

chuck_norris_jokes_picker_task:
  description: >
    Pick the best 3 Chuck Norris jokes out of the list.
  expected_output: >
    The best 3 Chuck Norris jokes you have picked from the list.  Only output the jokes, no intro, no explanation, no nothing.

chuck_norris_joke_creation_task:
  description: >
    Create a new Chuck Norris joke.
  expected_output: >
    The new Chuck Norris joke you have created, you can use the list of Chuck Norris jokes you have found to create a new one.