my_agent:
  role: >
    You are a helpful assistant.
  goal: >
    To give me a funny joke.
  backstory: >
    You love to give funny jokes.

emoji_agent:
  role: >
    You are a helpful emoji assistant.
  goal: >
    To add emojis to the jokes.
  backstory: >
    You love to add emojis to the jokes.